// packages/solid/src/jsx-runtime.ts
import type { JSX as SolidJSX } from "solid-js";
import type {
  DivStyle,
  FlexStyle,
  GridStyle,
  HostProps,
  TextStyle,
} from "@burokku/runtime";

interface WindowProps {
  children?: SolidJSX.Element;
  style?: never;
}

export namespace JSX {
  export type Element = SolidJSX.Element;

  export interface ElementChildrenAttribute {
    children: {};
  }

  export interface IntrinsicElements {
    window: WindowProps;
    div: HostProps<DivStyle>;
    flex: HostProps<FlexStyle>;
    grid: HostProps<GridStyle>;
    text: HostProps<TextStyle>;
  }
}

// packages/react/src/jsx-runtime.ts
import type { JSX as ReactJSX, Key, ReactNode } from "react";
import type { DivStyle, FlexStyle, GridStyle, TextStyle } from "@burokku/runtime";

export { Fragment, jsx, jsxs } from "react/jsx-runtime";

export interface ElementProps<Style> {
  key?: Key;
  children?: ReactNode;
  style?: Style;
}

export interface WindowProps {
  key?: Key;
  children?: ReactNode;
  style?: never;
}

export namespace JSX {
  export type Element = ReactJSX.Element;
  export interface ElementClass extends ReactJSX.ElementClass {}
  export interface ElementAttributesProperty extends ReactJSX.ElementAttributesProperty {}
  export interface ElementChildrenAttribute extends ReactJSX.ElementChildrenAttribute {}
  export type LibraryManagedAttributes<Component, Props> = ReactJSX.LibraryManagedAttributes<
    Component,
    Props
  >;
  export interface IntrinsicAttributes extends ReactJSX.IntrinsicAttributes {}
  export interface IntrinsicClassAttributes<T> extends ReactJSX.IntrinsicClassAttributes<T> {}
  export interface IntrinsicElements {
    window: WindowProps;
    div: ElementProps<DivStyle>;
    flex: ElementProps<FlexStyle>;
    grid: ElementProps<GridStyle>;
    text: ElementProps<TextStyle>;
  }
}
